test_that("Type bias", {
  expect_equal(optimal_return_doc(type = "binary"),
               "The output of the function is a `data.frame` object containing the optimization results:\n                 \\describe{\\item{u}{maximal expected utility under the optimization constraints, i.e. the expected utility of the optimal sample size and threshold value}\\item{RRgo}{optimal threshold value for the decision rule to go to phase III}\\item{n2}{total sample size for phase II; rounded to the next even natural number}\n                 \\item{n3}{total sample size for phase III; rounded to the next even natural number}\n                 \\item{n}{total sample size in the program; n = n2 + n3}\n                 \\item{K}{the cost constraint, Inf if no constraint is set}\n                 \\item{pgo}{probability to go to phase III}\n                 \\item{sProg}{probability of a successful program}\n                 \\item{sProg1}{probability of a successful program with \"small\" treatment effect in phase III}\n                 \\item{sProg2}{probability of a successful program with \"medium\" treatment effect in phase III}\n                 \\item{sProg3}{probability of a successful program with \"large\" treatment effect in phase III}\n                 \\item{K2}{expected costs for phase II}\n                 \\item{K3}{expected costs for phase III}}\n                 and further input parameters. Taking `cat(comment())` of the\n                 data frame lists the used optimization sequences, start and \n                 finish date of the optimization procedure."
               )})

test_that("multitrial_tte",{
  expect_equal(optimal_return_doc(type = "tte",setting = "multitrial"),
               "The output of the function is a `data.frame` object containing the optimization results:\n                 \\describe{\\item{Case}{Case: \"number of significant trials needed\"}\\item{Strategy}{Strategy: \"number of trials to be conducted in order to achieve the goal of the case\"}\\item{u}{maximal expected utility under the optimization constraints, i.e. the expected utility of the optimal sample size and threshold value}\\item{HRgo}{optimal threshold value for the decision rule to go to phase III}\n                        \\item{d2}{optimal total number of events for phase II}\n                        \\item{d3}{total expected number of events for phase III; rounded to next natural number}\n                        \\item{d}{total expected number of events in the program; d = d2 + d3}\\item{n2}{total sample size for phase II; rounded to the next even natural number}\n                 \\item{n3}{total sample size for phase III; rounded to the next even natural number}\n                 \\item{n}{total sample size in the program; n = n2 + n3}\n                 \\item{K}{the cost constraint, Inf if no constraint is set}\n                 \\item{pgo}{probability to go to phase III}\n                 \\item{sProg}{probability of a successful program}\n                 \\item{sProg1}{probability of a successful program with \"small\" treatment effect in phase III (lower boundary in HR scale is set to 1, as proposed by IQWiG (2016))}\n                 \\item{sProg2}{probability of a successful program with \"medium\" treatment effect in phase III (lower boundary in HR scale is set to 0.95, as proposed by IQWiG (2016))}\n                 \\item{sProg3}{probability of a successful program with \"large\" treatment effect in phase III (lower boundary in HR scale is set to 0.85, as proposed by IQWiG (2016))}\n                 \\item{K2}{expected costs for phase II}\n                 \\item{K3}{expected costs for phase III}}\n                 and further input parameters. Taking `cat(comment())` of the\n                 data frame lists the used optimization sequences, start and \n                 finish date of the optimization procedure.")
 })
